name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important for PR analysis

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest -q --maxfail=1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Sonar issues (API)
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: python scripts/fetch_sonar_issues.py

      - name: AI Reviewer (comment-only)
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: python scripts/llm_reviewer.py


      # (optional) your summary step
      - name: Post summary to PR
        run: python scripts/pr_commenter.py || true
