
name: ci

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: PYTHONPATH=. pytest -q --maxfail=1


      
 
      - name: SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fetch Sonar issues
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: python scripts/fetch_sonar_issues.py

      - name: Post summary to PR
        run: python scripts/pr_commenter.py

      - uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            issues.json
